version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  apt_packages:
    - build-essential
    - gfortran
    - libopenmpi-dev
    # - graphviz
  commands:
    - git clone --depth=1 https://github.com/snek5000/Nek5000_for_snek.git /home/docs/Nek5000
    - ls $NEK_SOURCE_ROOT
    - cat docs/conf.py
    - python -m virtualenv /home/docs/checkouts/readthedocs.org/user_builds/snek5000/envs/latest
    - /home/docs/checkouts/readthedocs.org/user_builds/snek5000/envs/latest/bin/python -m pip install --upgrade --no-cache-dir pip nox
    - /home/docs/checkouts/readthedocs.org/user_builds/snek5000/envs/latest/bin/python -m nox --session docs
    - mkdir _readthedocs
    - mv -r docs/_build/html _readthedocs

# Optionally set the version of Python and requirements required to build your
# docs
python:
  install:
    - requirements: requirements/docs.txt

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
