version: 2

# VCS submodules configuration
submodules:
  include: all
  recursive: true

build:
  apt_packages:
    - build-essential
    - gfortran
    - libopenmpi-dev

# Optionally set the version of Python and requirements required to build your
# docs
python:
  version: 3.8
  install:
    - requirements: requirements/docs.txt

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
