version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  apt_packages:
    - build-essential
    - gfortran
    - libopenmpi-dev
    # - graphviz
  jobs:
    pre_create_environment:
      # such that setuptools_scm can get the correct version
      - git checkout main
      - git pull --unshallow
    pre_build:
      - git clone --depth=1 https://github.com/snek5000/Nek5000_for_snek.git /home/docs/Nek5000
      - ls $NEK_SOURCE_ROOT
      - /home/docs/checkouts/readthedocs.org/user_builds/snek5000/envs/latest/bin/python docs/examples/scripts/tuto_phill.py
      - /home/docs/checkouts/readthedocs.org/user_builds/snek5000/envs/latest/bin/python docs/examples/scripts/tuto_cbox.py

# Optionally set the version of Python and requirements required to build your
# docs
python:
  install:
    - requirements: requirements/docs.txt

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
