version: 2

# VCS submodules configuration
submodules:
  include: all
  recursive: true

# Optionally set the version of Python and requirements required to build your
# docs
python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
         - docs
    - requirements: docs/requirements.txt

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
