channels:
  - conda-forge
  - defaults
dependencies:
  - libarchive
  - matplotlib-base
  - paraview
  - pip=21.0.1
  - python
  - zstd
  - pip:
    - breathe
    - bullet
    - flake8
    - fluidsim-core
    - fortran-language-server
    - inflection
    - ipython
    - jupyterlab
    - jupyterlab-git
    - notebook
    - pandas
    - pip-tools
    - pre-commit
    - pymech
    - pytest
    - pytest-cov
    - python-language-server
    - snakemake
    - sphinx
