name: deploy
on:
  workflow_dispatch:

jobs:
  pypi:
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name:
      run: |
        nox -s pypi --stop-on-first-error

